import { Medication, VitalSigns, Caregiver, UserProfile } from '@/types/medication';

export const mockMedications: Medication[] = [
  {
    id: '1',
    name: 'Telmisartan',
    dosage: '40mg',
    frequency: 'Once daily',
    times: ['08:00'],
    startDate: '2024-01-01',
    instructions: 'Take with water, preferably in the morning',
    prescribedBy: 'Dr. Priya Sharma',
    refillReminder: true,
    pillsRemaining: 25,
    totalPills: 30,
    isActive: true,
    adherenceRate: 95,
    totalDoses: 45,
    missedDoses: 2,
  },
  {
    id: '2',
    name: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice daily',
    times: ['08:00', '20:00'],
    startDate: '2024-01-01',
    instructions: 'Take with meals to reduce stomach upset',
    prescribedBy: 'Dr. Rajesh Kumar',
    refillReminder: true,
    pillsRemaining: 18,
    totalPills: 60,
    isActive: true,
    adherenceRate: 88,
    totalDoses: 90,
    missedDoses: 11,
  },
  {
    id: '3',
    name: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once daily',
    times: ['22:00'],
    startDate: '2024-01-15',
    instructions: 'Take in the evening with or without food',
    prescribedBy: 'Dr. Priya Sharma',
    refillReminder: true,
    pillsRemaining: 28,
    totalPills: 30,
    isActive: true,
    adherenceRate: 92,
    totalDoses: 30,
    missedDoses: 2,
  },
];

export const mockVitalSigns: VitalSigns[] = [
  {
    id: '1',
    timestamp: '2024-01-20T08:00:00Z',
    bloodPressure: { systolic: 125, diastolic: 80 },
    heartRate: 72,
    temperature: 98.6,
    oxygenSaturation: 98,
    weight: 65,
    bloodGlucose: 95,
  },
  {
    id: '2',
    timestamp: '2024-01-19T08:00:00Z',
    bloodPressure: { systolic: 122, diastolic: 78 },
    heartRate: 70,
    temperature: 98.4,
    oxygenSaturation: 99,
    weight: 64.5,
    bloodGlucose: 92,
  },
  {
    id: '3',
    timestamp: '2024-01-18T08:00:00Z',
    bloodPressure: { systolic: 128, diastolic: 82 },
    heartRate: 75,
    temperature: 98.8,
    oxygenSaturation: 97,
    weight: 65,
    bloodGlucose: 98,
  },
];

export const mockCaregivers: Caregiver[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    relationship: 'Daughter',
    email: 'priya.sharma@gmail.com',
    phone: '+91 98765 43210',
    role: 'primary',
    permissions: ['view_medications', 'view_health', 'emergency_contact'],
    isActive: true,
    lastActive: '2024-01-20T10:30:00Z',
  },
  {
    id: '2',
    name: 'Dr. Rajesh Kumar',
    relationship: 'Family Doctor',
    email: 'dr.rajesh@apollohospital.com',
    phone: '+91 11 2345 6789',
    role: 'medical',
    permissions: ['view_medications', 'view_health', 'modify_medications'],
    isActive: true,
    lastActive: '2024-01-19T14:00:00Z',
  },
  {
    id: '3',
    name: 'Amit Sharma',
    relationship: 'Son',
    email: 'amit.sharma@gmail.com',
    phone: '+91 98765 43211',
    role: 'secondary',
    permissions: ['view_medications', 'emergency_contact'],
    isActive: true,
    lastActive: '2024-01-18T20:15:00Z',
  },
  {
    id: '4',
    name: 'Dr. Sunita Verma',
    relationship: 'Cardiologist',
    email: 'dr.sunita@maxhealthcare.com',
    phone: '+91 11 4567 8901',
    role: 'medical',
    permissions: ['view_medications', 'view_health', 'modify_medications'],
    isActive: true,
    lastActive: '2024-01-17T16:45:00Z',
  },
];

export const mockUserProfile: UserProfile = {
  id: '1',
  name: 'Ramesh Kumar',
  email: 'ramesh.kumar@gmail.com',
  phone: '+91 98765 43210',
  dateOfBirth: '1955-03-15',
  medicalConditions: ['Hypertension', 'Type 2 Diabetes', 'High Cholesterol'],
  allergies: ['Penicillin', 'Shellfish'],
  bloodType: 'B+',
  emergencyContacts: [
    {
      id: '1',
      name: 'Priya Sharma',
      relationship: 'Daughter',
      phone: '+91 98765 43210',
      email: 'priya.sharma@gmail.com',
      isPrimary: true,
      isEmergencyService: false,
    },
    {
      id: '2',
      name: 'Emergency Services',
      relationship: 'Emergency',
      phone: '112',
      isPrimary: false,
      isEmergencyService: true,
    },
    {
      id: '3',
      name: 'Amit Sharma',
      relationship: 'Son',
      phone: '+91 98765 43211',
      email: 'amit.sharma@gmail.com',
      isPrimary: false,
      isEmergencyService: false,
    },
  ],
  insuranceInfo: {
    provider: 'Star Health Insurance',
    policyNumber: 'SHI123456789',
    groupNumber: 'GRP001',
  },
  preferences: {
    notifications: true,
    reminderSound: 'gentle',
    emergencyLocation: true,
    dataSharing: true,
  },
};